import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 1280, height: 900 });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle' });
await page.keyboard.press('Escape');
await page.waitForTimeout(1800);
await page.screenshot({ path: 'verify-hero-redesign.png' });
console.log('done');
await browser.close();
